# Site settings
title: TCLX
email: web@warwicktechcrew.co.uk
description: >
  Warwick Tech Crew's lighting stock
  
baseurl: "/lx-catalogue"
# Build settings
markdown: kramdown

plugins:
 - jekyll-coffeescript

whitelist:
  - jekyll-coffeescript
